# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'salesForceMobileApp' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'SmartStore'
pod 'SmartSync'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.8'
pod 'ZKSforce'

end

